version: '3'
services:
  influxdb:
    image: pabcargam/rasp_influxdb:latest
    volumes:
      - /home/pablodev/Desktop/NeliumAnalytics/TFG_appColectora/influxData:/var/lib/influxdb2
      - /home/pablodev/Desktop/NeliumAnalytics/TFG_appColectora/influxConfig:/etc/influxdb2
    ports:
      - "8086:8086"
    networks:
      - red-App

  telegraf:
    image: pabcargam/rasp_telegraf:latest
    links:
      - influxdb
    depends_on:
      - influxdb
    networks:
      - red-App

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DBadmin
      - POSTGRES_DB=authentication
    volumes:
      - pgpersistance:/var/lib/postgresql/data
    networks:
      - red-App

  backend:
    image: pabcargam/rasp_backend:latest
    depends_on:
      - postgres
    networks:
      - red-App

  cors:
    image: pabcargam/rasp_cors-anywhere
    ports:
      - "8080:8080"
    networks:
      - red-App

  frontend:
    image: pabcargam/rasp_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - red-App

volumes:
  pgpersistance:

networks:
  red-App:
    driver: bridge
